
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  fastapi_service_batch_processing:
    build:
      context: .  # Set the build context to the parent directory
      dockerfile: fastapi_service/Dockerfile  # Specify the Dockerfile location
    volumes:
      - ./myapp:/myapp  # Mount the myapp directory to /myapp in the container
    ports:
      - "80:8000"
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1  # Ensure Python output is flushed and displayed in real-time
      - WORKERS=4  # Number of Gunicorn workers
    command: ["gunicorn", "myapp.main:app", "--workers", "1", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000", "--log-level", "debug", "--access-logfile", "-", "--error-logfile","-"]

  celery_worker:
    build:
      context: .
      dockerfile: celery_worker/Dockerfile
    volumes:
      - ./myapp:/myapp  # Mount the myapp directory to /myapp in the container
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1  # Ensure Python output is flushed and displayed in real-time
      - CELERYD_CONCURRENCY=4  # Number of concurrent worker processes
    command: ["celery", "-A", "myapp.celery_app", "worker", "--loglevel=info", "--concurrency=1"]
