version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  fastapi_service_batch_processing:
    build:
      context: . # Set the build context to the parent directory (project/) in our case the (BATCH_VECTORIZATIO ...)
      dockerfile: fastapi_service/Dockerfile # Specify the Dockerfile location
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery_worker:
    build:
      context: .
      dockerfile: celery_worker/Dockerfile
    depends_on:
      - redis
